import java.util.ArrayList;
import java.util.HashMap;

/**
 * The {@code GenerateCampReportStaffMenu} class provides the execution logics of the staff's menu for generating the camp report.
 * The camp report generated by staff will contains the camp information, attendee list, and camp committee list, enquiry list, and suggesiton list.
 */
public class GenerateCampReportStaffMenu implements IMenu<Staff> {
	/**
	* Executes the menu logics for generating report.
	* The staff can choose to include or not include attendee list, committee list, enquiry list, and suggestion list.
	* The staff can also choose the attribute of enquiry and suggesiton to sort by (Ex. Sort by Date last updated)
	* The generated report file path will be shown in the user console.
	* @param staffObject               The staff that runs the menu
	*/
	public void runMenu(Staff staffObject) {
		ArrayList<Camp> campList = staffObject.createdCamps();
		ConsoleReaderInteger cri = new ConsoleReaderInteger();
		System.out.println("Choose the camp to generate report");
		for (int i=0;i<campList.size();i++) {
			System.out.printf("%d. %s\n", i+1, campList.get(i).getCampName());
		}
		try {
			Integer choice = cri.readFromConsole(1, campList.size());
			writeCampReportToDatabase(campList.get(choice-1), staffObject.getUserID());
		} catch (InputException e) {
			System.out.println(e.getMessage());
		}
	}

	/**
	* Writes the camp report to the database
	* @param camp                  The camp to write in the report
	* @param userID                The ID of staff generating the report
	*/
	public void writeCampReportToDatabase(Camp camp, String userID) {
		ArrayList<String> filterField = new ArrayList<>();
		filterField.add("Attendee");
		filterField.add("Committee");
		filterField.add("Enquiry");
		filterField.add("Suggestion");
		HashMap<String, Boolean> filter = new HashMap<>();
		ConsoleReaderString crs = new ConsoleReaderString();
		TXTFileReportDBWriter databaseWriter = new TXTFileReportDBWriter();
		for (String field: filterField) {
			System.out.printf("Do you want to include camp %s in the report? (y/n): ", field);
			try {
				String choice = crs.readFromConsole();
				if (choice.equals("y")) {
					filter.put(field, true);
				} else if (choice.equals("n")) {
					filter.put(field, false);
				} else {
					System.out.println("Invalid choice");
					return;
				}
			} catch(InputException e) {
				System.out.println(e.getMessage());
			}
		}
		databaseWriter.writeToDatabase(camp, filter, userID);
	}

	/**
	 * @return the menu description
	 */
	public String getMenuDescription () {
		return "Generate Camp Report";
	}
}
